## Egocentric action

name: Megalomeniac Exercise
on: [push]
run-name: ${{ github.actor }} is a megalomeniac
jobs:
  Find-me-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Find me
        id: find_me
        run: | 
            grep "Luca" ./README.md
      - name: Change something
        run: |
            find . -type f -name "*.md" -print0 | xargs -0 sed -i "s/foo/bar/g"
      - name: Commit
        if: steps.find_me.outputs == 'true'
        run: |
          git add *
          git commit -am "GH ACTION Headlines $(date)"
          git push origin main -f
      