## Unit testing

name: Unit testing
on: [push]

jobs:
  Unit-testing:
    runs-on: ubuntu-latest
    
    strategy: 
      matrix:
      python-version: [3.11]
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Pyhon
        uses: actions/setup-python@v4
        with: 
          python-version: ${{matrix.python-version}}
      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Run Pytest
        run: |
            pytest -v
            pytest --cov=app --cov-fail-under=90
